services:
  frontend:
    image: madelbert/todo-frontend:latest
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://nnairam.me:3000
    networks:
      - todo-network

  backend:
    image: madelbert/todo-backend:latest
    ports:
      - "3000:3000"
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge