version: '3'

services:
  # BACKEND: Node.js server
  backend:
    build: ./backend
    ports:
      - "3000:3000"  # backend server kuulab porti 3000
    networks:
      - app-network

  # FRONTEND: React app, serveeritud NGINX-i kaudu
  frontend:
    build: ./frontend
    ports:
      - "8080:80"  # React app teenindatakse port 81 kaudu
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
